name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 0.1.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  # image: ^2.1.13
  image: 2.1.12
  flutter_ume: '>=0.1.0 <0.2.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  flutter_coverage_badge: ^0.0.1+1

flutter:
